# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.6.0.schema.json
PackageIdentifier: DixonAppStudio.SofaDeck
PackageVersion: 1.0.1
MinimumOSVersion: 10.0.17763.0
ReleaseDate: 2026-09-29
Installers:
  - Architecture: x64
    InstallerType: nullsoft
    Scope: machine
    InstallModes:
      - interactive
      - silent
      - silentWithProgress
    InstallerSwitches:
      Silent: /S
      SilentWithProgress: /S
    UpgradeBehavior: install
    ProductCode: SofaDeck
    AppsAndFeaturesEntries:
      - DisplayName: SofaDeck
        DisplayVersion: 1.0.1
        Publisher: Dixon App Studio LLC
        ProductCode: SofaDeck
    InstallerUrl: https://www.sofadeck.com/download/SofaDeck-Setup-1.0.1-x64.exe
    InstallerSha256: 0A19CDA65D65EEE96D8DC10828A05E954C7336C4996CFA8E9FCE99057A1C702F
  - Architecture: arm64
    InstallerType: zip
    NestedInstallerType: portable
    NestedInstallerFiles:
      - RelativeFilePath: SofaDeck.exe
        PortableCommandAlias: sofadeck
    InstallerUrl: https://www.sofadeck.com/download/SofaDeck-1.0.1-windows-arm64.zip
    InstallerSha256: 487911A89C16480C59CD865A72A32355AA5985D8736EA253AD7AA763FAB630D4
ManifestType: installer
ManifestVersion: 1.6.0
